server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
    response-cache-update-interval-ms: 1000

# 開發環境日誌配置
logging:
  level:
    root: INFO
    '[com.example.registry]': DEBUG
    '[org.springframework.cloud.netflix.eureka]': DEBUG
    '[org.springframework.boot.actuate]': DEBUG
